/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2023-05-11

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm32f10x.h"
#include "port.h"
#include "debounceAvoid.h"
#include "lcd1602.h"
#include "dwt_delay.h"
#include "PID.h"

extern struct Key_TypeDef key1;
extern struct Key_TypeDef key2;
extern struct Key_TypeDef key3;
extern struct Key_TypeDef key4;
extern struct Keys_Properties keysProperties;

#define REFRESH_RATE 25 // Hz (Frames/s)

uint16_t cntr1 = 0;
uint16_t cntr2 = 0;
uint16_t increase = 0;
uint16_t input;
uint16_t x1;
uint16_t x2;

void init();

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
//
int main(void)
{

	init();
   delay_LCD(9000 * 16);
   InitLCD();
   DWT_init();
   InitPID(&PIDRegulator, 0, 0, 0, 100);
   SetLimits(&PIDRegulator, -1000, 1000);
   SetMode(&PIDRegulator, ON_ERROR);
   uint16_t refreshCntr = 0;

   while (1)
   {
   	if (_1kHz)
   	{
         RESET_1kHz;

         if (!(--sndDelay))
            SND_OFF;

         if (++refreshCntr >= (1000 / REFRESH_RATE))
         {
         	refreshCntr = 0;
            SET_REFRESH_LCD;
         }

         DebounceAvoid(&key1, &keysProperties);
         DebounceAvoid(&key2, &keysProperties);
         DebounceAvoid(&key3, &keysProperties);
         DebounceAvoid(&key4, &keysProperties);

         CalculateAverageADCValue(&adcData[0], ADC_DATA_ARR_LENGTH, &averageAdcData);

         x1 = (averageAdcData * 15) / 0xFFF;
         
         if (++cntr1 > 100)
         {
         	cntr1 = 0;
            PIDRegulator.setPoint = averageAdcData;
            PIDRegulator.input = input;

            increase = CalculateOutput(&PIDRegulator);
            input += increase;
         }

         x2 = Constrain(((input * 15) / 0xFFF), 0, 15);

         if (++cntr2 > 100)
         {
            cntr2 = 0;
            if (input > 5)
               input -= 5;
         }
      }

      if (_25Hz)
      {
         RESET_25Hz;

      }

      if (REFRESH_LCD)
      {
         RESET_REFRESH_LCD;

         if (CLEAR_LCD)
         {
            RESET_CLEAR_LCD;
            PutClear_LCD();
         }


         PutChr_LCD(_comm, 0x80 + x1);
         PutChr_LCD(_data, ' ');
         PutChr_LCD(_data, 'o');
         PutChr_LCD(_data, ' ');

         PutChr_LCD(_comm, 0x80 + x2);
         PutChr_LCD(_data, ' ');
         PutChr_LCD(_data, '*');
         PutChr_LCD(_data, ' ');

         //PutDgt_LCD(0, 0, 4, averageAdcData, 0, ' ');
         //PutDgt_LCD(6, 0, 4, input, 0, ' ');
         PutDgt_LCD(0, 0x40, 4, PIDRegulator.coefficients.Kp, 0, ' ');
         PutDgt_LCD(6, 0x40, 4, PIDRegulator.coefficients.Ki, 0, ' ');
         PutDgt_LCD(11, 0x40, 4, PIDRegulator.coefficients.Kd, 0, ' ');
      }

      if (KEY_READY)
      {
         RESET_KEY_READY;
         switch (keyCode)
         {
         case 0:
            PIDRegulator.coefficients.Kp = 0;
            PIDRegulator.coefficients.Ki = 0;
            PIDRegulator.coefficients.Kd = 0;
         	break;

         case 1:
            PIDRegulator.coefficients.Kp += 1;
            break;

         case 2:
            PIDRegulator.coefficients.Ki += 1;
            break;

         case 3:
            PIDRegulator.coefficients.Kd += 1;
            break;

         default:
            break;
         }
      }
   }
}

#ifdef  USE_FULL_ASSERT

/**
  * @brief  Reports the name of the source file and the source line number
  *   where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t* file, uint32_t line)
{
  /* User can add his own implementation to report the file name and line number,
     ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */

  /* Infinite loop */
  while (1)
  {
  }
}
#endif

/*
 * Minimal __assert_func used by the assert() macro
 * */
void __assert_func(const char *file, int line, const char *func, const char *failedexpr)
{
  while(1)
  {}
}

/*
 * Minimal __assert() uses __assert__func()
 * */
void __assert(const char *file, int line, const char *failedexpr)
{
   __assert_func (file, line, NULL, failedexpr);
}

#ifdef USE_SEE
#ifndef USE_DEFAULT_TIMEOUT_CALLBACK
/**
  * @brief  Basic management of the timeout situation.
  * @param  None.
  * @retval sEE_FAIL.
  */
uint32_t sEE_TIMEOUT_UserCallback(void)
{
  /* Return with error code */
  return sEE_FAIL;
}
#endif
#endif /* USE_SEE */

